name: Run AWS Glue Job

on:
  workflow_dispatch:

jobs:
  run-glue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run AWS Glue 4.0 Container
        run: |
          docker run --rm             -v $(pwd)/app/src:/home/glue_user/workspace/scripts             amazon/aws-glue-libs:glue_libs_4.0.0_image_01             /home/glue_user/jupyter/jupyter_start.sh -t GlueSparkSession             python /home/glue_user/workspace/scripts/my_glue_script.py
