name: Run AWS Glue Job (Local)

on:
  workflow_dispatch:

jobs:
  run-glue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull AWS Glue 4.0 Docker image
        run: |
          docker pull amazon/aws-glue-libs:glue_libs_4.0.0_image_01

      - name: Run AWS Glue 4.0 Container Locally
        run: |
          docker run --rm \
            -v $(pwd)/app/src:/home/glue_user/workspace/scripts \
            amazon/aws-glue-libs:glue_libs_4.0.0_image_01 \
            /home/glue_user/jupyter/jupyter_start.sh -t GlueSparkSession \
            python /home/glue_user/workspace/scripts/my_glue_script.py
